# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 018a26aa5686c3678f7c8042d0d694498cba3f83c09e683fcd78dfb792189115af9c0559da01d20704753b852fc4e5acc4b9664cf65d2d6526001590f5ffc302

test:
  secret_key_base: 741ec5a987a1e6b8e0f674dd49a7e37b8ba2abce27851584c484e37db73ea2227294b4f8a5a9d0a04ac1544f626a8541753b27c96c9c10de1d7848ab51e673d7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
